const AsyncHandler = require('express-async-handler');
const Navire = require('../../model/Navire');

exports.createNavire = AsyncHandler(async (req, res) => {
    const {
        ancien_nom,
        nom,
        longueur,
        largeur,
        imo,
        mmsi,
        type,
    } = req.body;



    const navire = await Navire.findOne({nom});
    if (navire) {
        throw new Error("Le navire existe déjà");
    }

    const navireCreated = await Navire.create({
        ancien_nom,
        nom,
        longueur,
        largeur,
        imo,
        mmsi,
        type,
    })
    res.status(201).json({
        status: "Success",
        message: "Le navire a été crée avec succès",
        data: navireCreated
    })
});

exports.getNavires = AsyncHandler(async (req, res) => {
    const naviresList = [
        {
            "_MMSI": "235095435",
            "_IMO": "1000019",
            "_NAME": "LADY K II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1961",
            "_BREADTH_EXTREME": "8.8",
            "_SUMMER_DWT": "164",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "3FOV",
            "_FLAG": "GB",
            "_DRAUGHT": "3.95",
            "_LENGTH_OVERALL": "57.6",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "15",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319904000",
            "_IMO": "1000021",
            "_NAME": "MONTKAJ",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1995",
            "_BREADTH_EXTREME": "13",
            "_SUMMER_DWT": "484",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCCB8",
            "_FLAG": "KY",
            "_DRAUGHT": "3.6",
            "_LENGTH_OVERALL": "78",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "AL BILAD",
            "_MANAGER": "AL BILAD",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "234028000",
            "_IMO": "1000033",
            "_NAME": "ASTRALIUM",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1995",
            "_BREADTH_EXTREME": "7.5",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MVWV7",
            "_FLAG": "GB",
            "_DRAUGHT": "",
            "_LENGTH_OVERALL": "31.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "11",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "403070000",
            "_IMO": "1000057",
            "_NAME": "LIMA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "20.9",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "HZIV",
            "_FLAG": "SA",
            "_DRAUGHT": "1.5",
            "_LENGTH_OVERALL": "30.48",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "233219000",
            "_IMO": "1000069",
            "_NAME": "LADY BEATRICE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1993",
            "_BREADTH_EXTREME": "10",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MRPW2",
            "_FLAG": "GB",
            "_DRAUGHT": "",
            "_LENGTH_OVERALL": "60",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "214464890",
            "_IMO": "1000100",
            "_NAME": "AQ",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "6.5",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SSSS",
            "_FLAG": "MD",
            "_DRAUGHT": "3.09",
            "_LENGTH_OVERALL": "29.32",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "239903700",
            "_IMO": "1000124",
            "_NAME": "THIRTY LOVE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "7.34",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVA6594",
            "_FLAG": "GR",
            "_DRAUGHT": "1.38",
            "_LENGTH_OVERALL": "30.1",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232398000",
            "_IMO": "1000150",
            "_NAME": "ADIX",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1984",
            "_BREADTH_EXTREME": "8.63",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GCGR",
            "_FLAG": "GB",
            "_DRAUGHT": "5.06",
            "_LENGTH_OVERALL": "67",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "11",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "229551000",
            "_IMO": "1000239",
            "_NAME": "LEGACY V",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "8.43",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HA3400",
            "_FLAG": "MT",
            "_DRAUGHT": "2.64",
            "_LENGTH_OVERALL": "48.6",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232347000",
            "_IMO": "1000241",
            "_NAME": "COMMITMENT",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "7.8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MXCM9",
            "_FLAG": "GB",
            "_DRAUGHT": "2.2",
            "_LENGTH_OVERALL": "36",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "14",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "300000000",
            "_IMO": "1000253",
            "_NAME": "AL FAHEDI",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "DP14",
            "_FLAG": "",
            "_DRAUGHT": "1.8",
            "_LENGTH_OVERALL": "44.82",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "27",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232576000",
            "_IMO": "1000265",
            "_NAME": "ALIA'N",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "10.6",
            "_SUMMER_DWT": "88",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "",
            "_FLAG": "GB",
            "_DRAUGHT": "1.1",
            "_LENGTH_OVERALL": "30.8",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "22",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "240439300",
            "_IMO": "1000277",
            "_NAME": "NOMMO",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "6",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVB2948",
            "_FLAG": "GR",
            "_DRAUGHT": "3.5",
            "_LENGTH_OVERALL": "28",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "5",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "319853000",
            "_IMO": "1000289",
            "_NAME": "ALL SEVEN",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "8.4",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZHBX7",
            "_FLAG": "KY",
            "_DRAUGHT": "2.2",
            "_LENGTH_OVERALL": "46.75",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "21",
            "_LIQUID_OIL": "",
            "_OWNER": "SNAS MARINE",
            "_MANAGER": "SNAS MARINE",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "310833000",
            "_IMO": "1000291",
            "_NAME": "ADAMAS V",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "9.77",
            "_SUMMER_DWT": "555",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCHE2",
            "_FLAG": "BM",
            "_DRAUGHT": "4.28",
            "_LENGTH_OVERALL": "61.78",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "22",
            "_SPEED_SERVICE": "22",
            "_LIQUID_OIL": "",
            "_OWNER": "ASPIN HOLDINGS",
            "_MANAGER": "ASPIN HOLDINGS",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "248652000",
            "_IMO": "1000320",
            "_NAME": "NAVTILVS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1973",
            "_BREADTH_EXTREME": "14.4",
            "_SUMMER_DWT": "2848",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HA4745",
            "_FLAG": "MT",
            "_DRAUGHT": "",
            "_LENGTH_OVERALL": "115.8",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "241841000",
            "_IMO": "1000394",
            "_NAME": "SOMETHING COOL",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1981",
            "_BREADTH_EXTREME": "7.56",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVB2686",
            "_FLAG": "GR",
            "_DRAUGHT": "2.13",
            "_LENGTH_OVERALL": "42.7",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "241765000",
            "_IMO": "1000409",
            "_NAME": "KASSANDRA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "8.59",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVB2717",
            "_FLAG": "GR",
            "_DRAUGHT": "3.6",
            "_LENGTH_OVERALL": "46.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "BALISEA SHIPPING",
            "_MANAGER": "BALISEA SHIPPING",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319229500",
            "_IMO": "1000423",
            "_NAME": "ISTROS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1954",
            "_BREADTH_EXTREME": "6.89",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGQL3",
            "_FLAG": "KY",
            "_DRAUGHT": "2.83",
            "_LENGTH_OVERALL": "42.09",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319854000",
            "_IMO": "1000447",
            "_NAME": "VA BENE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "8.95",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCIP8",
            "_FLAG": "KY",
            "_DRAUGHT": "2.4",
            "_LENGTH_OVERALL": "43.8",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "GLEN WYLLIN",
            "_MANAGER": "GLEN WYLLIN",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "244127366",
            "_IMO": "1000576",
            "_NAME": "TIZIANA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1963",
            "_BREADTH_EXTREME": "7.41",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "PI2382",
            "_FLAG": "NL",
            "_DRAUGHT": "3.17",
            "_LENGTH_OVERALL": "35.59",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "636009659",
            "_IMO": "1000588",
            "_NAME": "ASTARTE II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "11.2",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ELOU4",
            "_FLAG": "LR",
            "_DRAUGHT": "4",
            "_LENGTH_OVERALL": "65.2",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "KASTRO",
            "_MANAGER": "KASTRO",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232035982",
            "_IMO": "1000617",
            "_NAME": "GOOSE",
            "_PLACE_OF_BUILD": "LONDON U.K.",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "7.62",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MJFM5",
            "_FLAG": "GB",
            "_DRAUGHT": "2.54",
            "_LENGTH_OVERALL": "41.03",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "235031582",
            "_IMO": "1000629",
            "_NAME": "LADY ANNA OF FIFE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "6",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MQWX3",
            "_FLAG": "GB",
            "_DRAUGHT": "2",
            "_LENGTH_OVERALL": "30.48",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "503188700",
            "_IMO": "1000631",
            "_NAME": "ATLANTIC PRINCESS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "6",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "VNAP",
            "_FLAG": "AU",
            "_DRAUGHT": "2.3",
            "_LENGTH_OVERALL": "25",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "225366000",
            "_IMO": "1000655",
            "_NAME": "CERVANTES SAAVEDRA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1934",
            "_BREADTH_EXTREME": "7.71",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ECEZ",
            "_FLAG": "ES",
            "_DRAUGHT": "3.99",
            "_LENGTH_OVERALL": "34.4",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "310013000",
            "_IMO": "1000667",
            "_NAME": "ATLANTIS II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1981",
            "_BREADTH_EXTREME": "14.43",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "VSBQ9",
            "_FLAG": "BM",
            "_DRAUGHT": "4.28",
            "_LENGTH_OVERALL": "115.82",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "21.5",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "247204310",
            "_IMO": "1000710",
            "_NAME": "AWAYS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "9.3",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "IN8608",
            "_FLAG": "IT",
            "_DRAUGHT": "2.74",
            "_LENGTH_OVERALL": "49.58",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "17",
            "_SPEED_SERVICE": "17",
            "_LIQUID_OIL": "",
            "_OWNER": "FAR AWAY",
            "_MANAGER": "NAUTICA TAVERNA",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "241708000",
            "_IMO": "1000734",
            "_NAME": "ITOTO",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "9.25",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVB2095",
            "_FLAG": "GR",
            "_DRAUGHT": "3.77",
            "_LENGTH_OVERALL": "61",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "19",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "255996000",
            "_IMO": "1000851",
            "_NAME": "COSTA MAGNA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1983",
            "_BREADTH_EXTREME": "7.48",
            "_SUMMER_DWT": "72",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "CQTV",
            "_FLAG": "PT",
            "_DRAUGHT": "2",
            "_LENGTH_OVERALL": "43.45",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12.5",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SPECIAL VESSEL"
        },
        {
            "_MMSI": "735059321",
            "_IMO": "1000887",
            "_NAME": "PASSION",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1973",
            "_BREADTH_EXTREME": "8.64",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "HC6513",
            "_FLAG": "EC",
            "_DRAUGHT": "3.15",
            "_LENGTH_OVERALL": "43.72",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "THIERRY VOISIN PARTNERSHIP",
            "_MANAGER": "THIERRY VOISIN PARTNERSHIP",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "215606000",
            "_IMO": "1000899",
            "_NAME": "BE MINE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "8.13",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HA2755",
            "_FLAG": "MT",
            "_DRAUGHT": "2",
            "_LENGTH_OVERALL": "40.35",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "235116047",
            "_IMO": "1000916",
            "_NAME": "BETYSMINK III",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1975",
            "_BREADTH_EXTREME": "3.81",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "2GWR",
            "_FLAG": "GB",
            "_DRAUGHT": "1.98",
            "_LENGTH_OVERALL": "13.42",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "232049174",
            "_IMO": "1000954",
            "_NAME": "CHESELLA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1983",
            "_BREADTH_EXTREME": "7.01",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "245",
            "_CALLSIGN": "MOBI8",
            "_FLAG": "GB",
            "_DRAUGHT": "2.65",
            "_LENGTH_OVERALL": "37.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "310547000",
            "_IMO": "1001051",
            "_NAME": "NAFISA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "8.71",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCAX6",
            "_FLAG": "BM",
            "_DRAUGHT": "2.9",
            "_LENGTH_OVERALL": "49.25",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232111000",
            "_IMO": "1001130",
            "_NAME": "CAPELLA C",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1968",
            "_BREADTH_EXTREME": "10.53",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GFVB",
            "_FLAG": "GB",
            "_DRAUGHT": "3.85",
            "_LENGTH_OVERALL": "59",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "518100572",
            "_IMO": "1001142",
            "_NAME": "THE ONE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1973",
            "_BREADTH_EXTREME": "9",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "E5U3486",
            "_FLAG": "CK",
            "_DRAUGHT": "3",
            "_LENGTH_OVERALL": "71",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "22",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "518604000",
            "_IMO": "1001166",
            "_NAME": "SPREZZATURA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1971",
            "_BREADTH_EXTREME": "6.13",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "E5U2551",
            "_FLAG": "CK",
            "_DRAUGHT": "1.73",
            "_LENGTH_OVERALL": "30.28",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "15",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319822000",
            "_IMO": "1001178",
            "_NAME": "AMARA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "10",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZC0F3",
            "_FLAG": "KY",
            "_DRAUGHT": "3.3",
            "_LENGTH_OVERALL": "57",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "CONFRESI BAY",
            "_MANAGER": "CONFRESI BAY",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "236022000",
            "_IMO": "1001180",
            "_NAME": "CEDAR SEA II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "10.35",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZDCY7",
            "_FLAG": "GI",
            "_DRAUGHT": "3.25",
            "_LENGTH_OVERALL": "65",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "310125000",
            "_IMO": "1001192",
            "_NAME": "BAD GIRL",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "9.85",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCBC9",
            "_FLAG": "BM",
            "_DRAUGHT": "2.08",
            "_LENGTH_OVERALL": "56.74",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "25",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "229237000",
            "_IMO": "1001207",
            "_NAME": "ARIONAS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1967",
            "_BREADTH_EXTREME": "7.31",
            "_SUMMER_DWT": "49",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HB7938",
            "_FLAG": "MT",
            "_DRAUGHT": "3",
            "_LENGTH_OVERALL": "36.6",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "247271500",
            "_IMO": "1001219",
            "_NAME": "HAPPYSSIMA DEI GALLI",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "7",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "IN7557",
            "_FLAG": "IT",
            "_DRAUGHT": "2.2",
            "_LENGTH_OVERALL": "34.7",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "13",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319098100",
            "_IMO": "1001257",
            "_NAME": "LITTLE STAR",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1993",
            "_BREADTH_EXTREME": "7.27",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGFQ5",
            "_FLAG": "KY",
            "_DRAUGHT": "1.98",
            "_LENGTH_OVERALL": "36.75",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "376106000",
            "_IMO": "1001386",
            "_NAME": "DEIANEIRA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1951",
            "_BREADTH_EXTREME": "6.34",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "J8Y2905",
            "_FLAG": "VC",
            "_DRAUGHT": "2.74",
            "_LENGTH_OVERALL": "38.12",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "470000001",
            "_IMO": "1001415",
            "_NAME": "DHAFIR",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1980",
            "_BREADTH_EXTREME": "7.5",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "A6E2075",
            "_FLAG": "AE",
            "_DRAUGHT": "2.04",
            "_LENGTH_OVERALL": "40.56",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319157800",
            "_IMO": "1001477",
            "_NAME": "JAMEEL",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1985",
            "_BREADTH_EXTREME": "7.77",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGID3",
            "_FLAG": "KY",
            "_DRAUGHT": "2.31",
            "_LENGTH_OVERALL": "44.04",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "SETE YACHT MANAGEMENT",
            "_MANAGER": "SETE YACHT MANAGEMENT",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "339310000",
            "_IMO": "1001489",
            "_NAME": "RENA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "7.7",
            "_SUMMER_DWT": "300",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "6YRR5",
            "_FLAG": "JM",
            "_DRAUGHT": "2.13",
            "_LENGTH_OVERALL": "39.62",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "375081000",
            "_IMO": "1001506",
            "_NAME": "ZEUS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "11.2",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "J8Y2410",
            "_FLAG": "VC",
            "_DRAUGHT": "3.4",
            "_LENGTH_OVERALL": "74.1",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "38",
            "_SPEED_SERVICE": "35",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319908000",
            "_IMO": "1001544",
            "_NAME": "SHAHNAZ",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "11",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCCD2",
            "_FLAG": "KY",
            "_DRAUGHT": "3.2",
            "_LENGTH_OVERALL": "63.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "413805923",
            "_IMO": "1001568",
            "_NAME": "YUXINHUO2657",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "3.36",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "",
            "_FLAG": "CN",
            "_DRAUGHT": "1.83",
            "_LENGTH_OVERALL": "10.98",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "319501000",
            "_IMO": "1001570",
            "_NAME": "A AND A",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1966",
            "_BREADTH_EXTREME": "8.02",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGBA7",
            "_FLAG": "KY",
            "_DRAUGHT": "3.27",
            "_LENGTH_OVERALL": "44.68",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "247387000",
            "_IMO": "1001611",
            "_NAME": "F100",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1983",
            "_BREADTH_EXTREME": "7.75",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "IZ9520",
            "_FLAG": "IT",
            "_DRAUGHT": "2",
            "_LENGTH_OVERALL": "30.53",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "525024066",
            "_IMO": "1001635",
            "_NAME": "PELAGIAN",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1965",
            "_BREADTH_EXTREME": "7.19",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "YB5363",
            "_FLAG": "ID",
            "_DRAUGHT": "3.2",
            "_LENGTH_OVERALL": "34.48",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "470725000",
            "_IMO": "1001659",
            "_NAME": "FINESSE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1978",
            "_BREADTH_EXTREME": "7.74",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "A6E2919",
            "_FLAG": "AE",
            "_DRAUGHT": "3.05",
            "_LENGTH_OVERALL": "45.93",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "SULTAN AHMED",
            "_MANAGER": "SULTAN AHMED",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "244710298",
            "_IMO": "1001685",
            "_NAME": "LIZA MARLEEN",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "4.18",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "PC2705",
            "_FLAG": "NL",
            "_DRAUGHT": "1.83",
            "_LENGTH_OVERALL": "13.26",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "239632600",
            "_IMO": "1001702",
            "_NAME": "FLEURTJE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1960",
            "_BREADTH_EXTREME": "8.57",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "SVA3639",
            "_FLAG": "GR",
            "_DRAUGHT": "4.63",
            "_LENGTH_OVERALL": "52.06",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "229739000",
            "_IMO": "1001829",
            "_NAME": "NATALIA V",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "8.4",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "320",
            "_CALLSIGN": "9M550",
            "_FLAG": "MT",
            "_DRAUGHT": "2.4",
            "_LENGTH_OVERALL": "45.25",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "15.2",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "235148000",
            "_IMO": "1001831",
            "_NAME": "GIRIZ II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1964",
            "_BREADTH_EXTREME": "8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "E5U2499",
            "_FLAG": "GB",
            "_DRAUGHT": "2.74",
            "_LENGTH_OVERALL": "26",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "366990760",
            "_IMO": "1001867",
            "_NAME": "AVALON",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "6.71",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "WDC2295",
            "_FLAG": "US",
            "_DRAUGHT": "3.18",
            "_LENGTH_OVERALL": "29.78",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "310065000",
            "_IMO": "1001881",
            "_NAME": "GRAND OCEAN",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "13",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCAI8",
            "_FLAG": "BM",
            "_DRAUGHT": "4.2",
            "_LENGTH_OVERALL": "80",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "SSH MARITIME MANAGEMENT",
            "_MANAGER": "SSH MARITIME MANAGEMENT",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "255913598",
            "_IMO": "1001922",
            "_NAME": "CLOUD ATLAS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "8.5",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "CRXG5",
            "_FLAG": "PT",
            "_DRAUGHT": "3",
            "_LENGTH_OVERALL": "47",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319022000",
            "_IMO": "1001934",
            "_NAME": "HASABI II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1950",
            "_BREADTH_EXTREME": "9.39",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCPG3",
            "_FLAG": "KY",
            "_DRAUGHT": "",
            "_LENGTH_OVERALL": "58.28",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "229696000",
            "_IMO": "1001960",
            "_NAME": "CURIOSITY",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1985",
            "_BREADTH_EXTREME": "7.54",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HA3526",
            "_FLAG": "MT",
            "_DRAUGHT": "2.46",
            "_LENGTH_OVERALL": "42.36",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319574000",
            "_IMO": "1001984",
            "_NAME": "IL VAGABONDO",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "10.98",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZHBZ3",
            "_FLAG": "KY",
            "_DRAUGHT": "3.29",
            "_LENGTH_OVERALL": "61.27",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "19",
            "_LIQUID_OIL": "",
            "_OWNER": "JAMEENA",
            "_MANAGER": "JAMEENA",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "538080081",
            "_IMO": "1002017",
            "_NAME": "LEGEND",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1987",
            "_BREADTH_EXTREME": "9.1",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "V7IE6",
            "_FLAG": "MH",
            "_DRAUGHT": "3",
            "_LENGTH_OVERALL": "51.25",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "DB MARINE CONSULTING",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319393000",
            "_IMO": "1002055",
            "_NAME": "ITASCA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1961",
            "_BREADTH_EXTREME": "10.47",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGHI",
            "_FLAG": "KY",
            "_DRAUGHT": "4.69",
            "_LENGTH_OVERALL": "53.98",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232008000",
            "_IMO": "1002081",
            "_NAME": "JAGARE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1981",
            "_BREADTH_EXTREME": "8.08",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GBZA",
            "_FLAG": "GB",
            "_DRAUGHT": "3.5",
            "_LENGTH_OVERALL": "36.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "319706000",
            "_IMO": "1002093",
            "_NAME": "TRANQUILLITY",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1984",
            "_BREADTH_EXTREME": "8.29",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCGY5",
            "_FLAG": "KY",
            "_DRAUGHT": "2.5",
            "_LENGTH_OVERALL": "42.02",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232059000",
            "_IMO": "1002172",
            "_NAME": "KALINGA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1982",
            "_BREADTH_EXTREME": "8.8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GCRT",
            "_FLAG": "GB",
            "_DRAUGHT": "2.98",
            "_LENGTH_OVERALL": "50.65",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "SETE YACHT MANAGEMENT",
            "_MANAGER": "SETE YACHT MANAGEMENT",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "235019268",
            "_IMO": "1002184",
            "_NAME": "C SIDE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1979",
            "_BREADTH_EXTREME": "7.01",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GCRQ",
            "_FLAG": "GB",
            "_DRAUGHT": "2.19",
            "_LENGTH_OVERALL": "34.52",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "403299000",
            "_IMO": "1002213",
            "_NAME": "KINGDOM 5 KR",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1980",
            "_BREADTH_EXTREME": "13.23",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "HZMM",
            "_FLAG": "SA",
            "_DRAUGHT": "",
            "_LENGTH_OVERALL": "86.01",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "20",
            "_LIQUID_OIL": "",
            "_OWNER": "KINGDOM HOLDING",
            "_MANAGER": "BURGESS YACHTS",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "538070946",
            "_IMO": "1002225",
            "_NAME": "GLACIAL BEAR",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1993",
            "_BREADTH_EXTREME": "9.3",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "320",
            "_CALLSIGN": "V7BT2",
            "_FLAG": "MH",
            "_DRAUGHT": "2.7",
            "_LENGTH_OVERALL": "39.6",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "12",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319179000",
            "_IMO": "1002249",
            "_NAME": "MY BROTHER BRANCUSI",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1966",
            "_BREADTH_EXTREME": "10.6",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZGWH",
            "_FLAG": "KY",
            "_DRAUGHT": "4.81",
            "_LENGTH_OVERALL": "66.73",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12.5",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232205000",
            "_IMO": "1002275",
            "_NAME": "LADY GEORGINA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1982",
            "_BREADTH_EXTREME": "8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GCSF",
            "_FLAG": "GB",
            "_DRAUGHT": "2.9",
            "_LENGTH_OVERALL": "45",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "CORNICHE INVESTMENTS",
            "_MANAGER": "CORNICHE INVESTMENTS",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319699000",
            "_IMO": "1002328",
            "_NAME": "ACHILLES",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1984",
            "_BREADTH_EXTREME": "7.93",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCGP9",
            "_FLAG": "KY",
            "_DRAUGHT": "3.86",
            "_LENGTH_OVERALL": "53.31",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "20",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "538071648",
            "_IMO": "1002342",
            "_NAME": "RAMBLE ON",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1991",
            "_BREADTH_EXTREME": "8.8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "V7A4961",
            "_FLAG": "MH",
            "_DRAUGHT": "2.8",
            "_LENGTH_OVERALL": "43.6",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "PINK SANDS HOLDINGS",
            "_MANAGER": "PINK SANDS HOLDINGS",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "538071262",
            "_IMO": "1002378",
            "_NAME": "DANCING HARE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "9.2",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "V7IP2",
            "_FLAG": "MH",
            "_DRAUGHT": "4.01",
            "_LENGTH_OVERALL": "57.5",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "TOUILLE",
            "_MANAGER": "TOUILLE",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "309221000",
            "_IMO": "1002380",
            "_NAME": "LADY MOURA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "18.52",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "C6IU6",
            "_FLAG": "BS",
            "_DRAUGHT": "5.51",
            "_LENGTH_OVERALL": "105",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "22",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232060000",
            "_IMO": "1002392",
            "_NAME": "LADY SARYA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1972",
            "_BREADTH_EXTREME": "11.65",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GDRC",
            "_FLAG": "GB",
            "_DRAUGHT": "4.17",
            "_LENGTH_OVERALL": "76.37",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "21",
            "_LIQUID_OIL": "",
            "_OWNER": "SETE YACHT MANAGEMENT",
            "_MANAGER": "SETE YACHT MANAGEMENT",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "253081000",
            "_IMO": "1002407",
            "_NAME": "CAROLINE SEA II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "7.62",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "LXCU",
            "_FLAG": "LU",
            "_DRAUGHT": "3.26",
            "_LENGTH_OVERALL": "43.07",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "15",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319203900",
            "_IMO": "1002445",
            "_NAME": "MESERRET 3",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1992",
            "_BREADTH_EXTREME": "13",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZG0C9",
            "_FLAG": "KY",
            "_DRAUGHT": "4.5",
            "_LENGTH_OVERALL": "75",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "19",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "335150000",
            "_IMO": "1002469",
            "_NAME": "LE PHARAON",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "9.85",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "HO3121",
            "_FLAG": "",
            "_DRAUGHT": "3.1",
            "_LENGTH_OVERALL": "59.2",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15.5",
            "_LIQUID_OIL": "",
            "_OWNER": "LAITH TRADING & CONTRACTING",
            "_MANAGER": "LAITH TRADING & CONTRACTING",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232049488",
            "_IMO": "1002471",
            "_NAME": "LADY HAYAT",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1982",
            "_BREADTH_EXTREME": "8.23",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MOCU4",
            "_FLAG": "GB",
            "_DRAUGHT": "3",
            "_LENGTH_OVERALL": "47.24",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "BLIXSETH GROUP WASHINGTON",
            "_MANAGER": "BLIXSETH GROUP WASHINGTON",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232003690",
            "_IMO": "1002495",
            "_NAME": "LORD NELSON",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "8.65",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GHJV",
            "_FLAG": "GB",
            "_DRAUGHT": "4.1",
            "_LENGTH_OVERALL": "52.2",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "248817000",
            "_IMO": "1002536",
            "_NAME": "CHEETAH MOON",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "7.54",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HB2078",
            "_FLAG": "MT",
            "_DRAUGHT": "2.2",
            "_LENGTH_OVERALL": "38.36",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "212462000",
            "_IMO": "1002550",
            "_NAME": "MALCOLM MILLER",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1968",
            "_BREADTH_EXTREME": "7.62",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "5BZU3",
            "_FLAG": "CY",
            "_DRAUGHT": "4.81",
            "_LENGTH_OVERALL": "41.17",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "378018000",
            "_IMO": "1002562",
            "_NAME": "ELENVAR",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1988",
            "_BREADTH_EXTREME": "7.5",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZJL6703",
            "_FLAG": "VG",
            "_DRAUGHT": "4",
            "_LENGTH_OVERALL": "31.7",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "466245000",
            "_IMO": "1002598",
            "_NAME": "MARACUNDA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "10.17",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "",
            "_FLAG": "QA",
            "_DRAUGHT": "2.67",
            "_LENGTH_OVERALL": "49.95",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "18",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "518100386",
            "_IMO": "1002603",
            "_NAME": "MARALA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1931",
            "_BREADTH_EXTREME": "8.08",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "E5U3302",
            "_FLAG": "CK",
            "_DRAUGHT": "3.23",
            "_LENGTH_OVERALL": "58.86",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "215607000",
            "_IMO": "1002627",
            "_NAME": "THE MERCY BOYS",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1986",
            "_BREADTH_EXTREME": "9",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "9HA2770",
            "_FLAG": "MT",
            "_DRAUGHT": "3.5",
            "_LENGTH_OVERALL": "49",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "17",
            "_LIQUID_OIL": "",
            "_OWNER": "HILL ROBINSON YACHT MANAGEMENT CONSULTANTS",
            "_MANAGER": "HILL ROBINSON YACHT MANAGEMENT CONSULTANTS",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "235241000",
            "_IMO": "1002641",
            "_NAME": "MARIDOME",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1989",
            "_BREADTH_EXTREME": "11.8",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MKVM5",
            "_FLAG": "GB",
            "_DRAUGHT": "3.2",
            "_LENGTH_OVERALL": "54",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "WILSON YACHT MANAGEMENT",
            "_MANAGER": "WILSON YACHT MANAGEMENT",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "232607000",
            "_IMO": "1002653",
            "_NAME": "ELECTA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1990",
            "_BREADTH_EXTREME": "7.76",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "MLRW3",
            "_FLAG": "GB",
            "_DRAUGHT": "2.31",
            "_LENGTH_OVERALL": "36.68",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "13",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SAILING VESSEL"
        },
        {
            "_MMSI": "403005000",
            "_IMO": "1002677",
            "_NAME": "AL DIRIYAH",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1960",
            "_BREADTH_EXTREME": "11.31",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "HZAD",
            "_FLAG": "SA",
            "_DRAUGHT": "4.2",
            "_LENGTH_OVERALL": "78.65",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "",
            "_LIQUID_OIL": "",
            "_OWNER": "RED SEA MANAGEMENT INTERNATIONAL",
            "_MANAGER": "RED SEA MANAGEMENT INTERNATIONAL",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "314094000",
            "_IMO": "1002691",
            "_NAME": "MONACO",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1981",
            "_BREADTH_EXTREME": "7.01",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "8POP",
            "_FLAG": "BB",
            "_DRAUGHT": "2.74",
            "_LENGTH_OVERALL": "37.9",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "15",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "310034000",
            "_IMO": "1002706",
            "_NAME": "MMM",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1993",
            "_BREADTH_EXTREME": "9.21",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCAU2",
            "_FLAG": "BM",
            "_DRAUGHT": "3.83",
            "_LENGTH_OVERALL": "46",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "14",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "538080084",
            "_IMO": "1002718",
            "_NAME": "BERZINC",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1978",
            "_BREADTH_EXTREME": "7.15",
            "_SUMMER_DWT": "59",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "V7DG2",
            "_FLAG": "MH",
            "_DRAUGHT": "2",
            "_LENGTH_OVERALL": "44.2",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "12",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "EXMAR SHIPMANAGEMENT NV",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "SPECIAL VESSEL"
        },
        {
            "_MMSI": "518998266",
            "_IMO": "1002720",
            "_NAME": "AZTECA",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1983",
            "_BREADTH_EXTREME": "8.38",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "E5U4246",
            "_FLAG": "CK",
            "_DRAUGHT": "2.44",
            "_LENGTH_OVERALL": "44.83",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "22",
            "_LIQUID_OIL": "",
            "_OWNER": "",
            "_MANAGER": "",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "233731000",
            "_IMO": "1002756",
            "_NAME": "MICHAELA ROSE",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1984",
            "_BREADTH_EXTREME": "8.72",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "GDQF",
            "_FLAG": "GB",
            "_DRAUGHT": "2.89",
            "_LENGTH_OVERALL": "49.25",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "16",
            "_LIQUID_OIL": "",
            "_OWNER": "ROCHELLE MARINE",
            "_MANAGER": "ROCHELLE MARINE",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        },
        {
            "_MMSI": "319204000",
            "_IMO": "1002768",
            "_NAME": "MESERRET II",
            "_PLACE_OF_BUILD": "",
            "_BUILD": "1978",
            "_BREADTH_EXTREME": "9.6",
            "_SUMMER_DWT": "",
            "_DISPLACEMENT_SUMMER": "",
            "_CALLSIGN": "ZCGM3",
            "_FLAG": "KY",
            "_DRAUGHT": "3.26",
            "_LENGTH_OVERALL": "57.24",
            "_FUEL_CONSUMPTION": "",
            "_SPEED_MAX": "",
            "_SPEED_SERVICE": "17",
            "_LIQUID_OIL": "",
            "_OWNER": "THETIS SHIPHOLDING",
            "_MANAGER": "THETIS SHIPHOLDING",
            "_FINANCIAL_OWNER": "",
            "_TECHNICAL_MANAGER": "",
            "_VESSEL_TYPE": "YACHT"
        }
    ]
    const navires = await Navire.find();
    res.status(200).json({
        status: "success",
        message: "La liste des navires ont été récupéré avec succès",
        data: navires
    })
});

exports.getNavire = AsyncHandler(async (req, res) => {
    const navire = await Navire.findById(req.params.id);
    res.status(200).json({
        status: "success",
        message: "Le navire a été récupéré avec succès",
        data: navire
    });
});


exports.getNaviresByImoOrMmsi = AsyncHandler(async (req, res) => {
    const {valeur} = req.query;

    if (!valeur) {
        return res.status(400).json({message: 'Le champ de recherche est requis'});
    }
    // Créer un objet de filtre pour rechercher les navires en fonction du champ
    const filter = {
        $or: [
            {nom: {$regex: valeur, $options: 'i'}}, // Recherche insensible à la casse dans le nom
            {imo: valeur},
            {mmsi: valeur},
        ],
    };


    // Rechercher la liste des navires en fonction du filtre
    const navires = await Navire.find(filter);

    if (!navires) {
        throw new Error(`Le navire n'existe pas`);
    }
    res.status(200).json({
        status: "success",
        message: "Le navire a été modifié avec succès",
        data: navires
    })

})
exports.updateNavire = AsyncHandler(async (req, res) => {
    const {
        ancien_nom,
        nom,
        longueur,
        largeur,
        imo,
        mmsi,
        type,
    } = req.body;
    const createNavireFound = await Navire.find({nom});
    if (createNavireFound) {
        throw new Error("Le navire existe déjà.");
    }
    const navire = await Navire.findByIdAndUpdate(
        req.params.id,
        {
            ancien_nom,
            nom,
            code_radio,
            longueur,
            largeur,
            imo,
            mmsi,
            tirant_eau,
            type,
            volume,
            tirant_eau_arriere,
            tirant_eau_avant
        }, {
            new: true,
        }
    );
    res.status(200).json({
        status: "success",
        message: "Le navire a été modifié avec succès",
        data: navire
    })

})

exports.deleteNavire = AsyncHandler(async (req, res) => {
    await Navire.findByIdAndDelete(req.params.id);
    res.status(200).json({
        status: "success",
        message: "Le navire a été supprimé avec succès",
    })
});
