export const TypeDocument = {
    SHIP_PARTICULAR: 'SHIP_PARTICULAR',
    MASTER_DECLARATION: 'MASTER_DECLARATION',
    CARGO_MANIFEST: 'CARGO_MANIFEST',
    DANGEROUS_GOODS: 'DANGEROUS_GOODS',
    CREW_LIST: 'CREW_LIST',
    LAST_10_PORT: 'LAST_10_PORT',
    MARITIME_POLLUTION: 'MARITIME_POLLUTION',
    AVAN_FORM: 'AVAN_FORM',
    MARITIME_DECLARATION_HEALTH: 'MARITIME_DECLARATION_HEALTH',
};

